### ISSUE TITLE
How to install on Windows

### ISSUE THREAD

**Issue by dofrenador** [corneliusweig/konfig#38]
Can you elaborate on the download instruction for Windows? I and downloading the konfig and putting it in my path variables as konfig.exe but it does not work
![Capture](https://user-images.githubusercontent.com/32098276/128487520-4830747b-9f81-46ac-8a17-a7589d0cd0ff.PNG)
![a](https://user-images.githubusercontent.com/32098276/128487917-7364c333-1108-4a57-b36e-fbda72771cb2.PNG)
I have also tried to restart my computer but could not get it to work

**Comment by corneliusweig** [comment]
I am not sure. I think it is possible, but I haven't tried it out. It is also not supported when installing via krew.

If you can figure out how it's done, feel free to send a PR. Until then, I'll remove the docs about Win support. Sorry :pray:

**Comment by LukasHeimann** [comment]
I got it to work in `git bash` when I replaced `IFS=$':\n\t'` in the script with `IFS=$';\n\t'`, as windows uses semicolon instead of colons for arrayed environment variables.

That being said, I think krew can't distribute bash scripts on windows, and assuming git bash just isn't general, so I won't be proposing a PR and just leave this comment.
